fs=require('fs')
// fs.writeFileSync('lec1.txt','JSON')
// fs.appendFileSync('lec1.txt','node')
// data=fs.readFileSync('lec1.txt','utf-8')
// console.log(data)
// console.log('process end')
// fs.copyFileSync('lec1.txt','lec2.txt')
// fs.renameSync('lec1.txt','data.txt')
// fs.unlinkSync('lec2.txt')