let fs=require('fs')
// fs.mkdirSync('b2')
// fs.writeFileSync('b2/lec.txt','module')
// fs.renameSync('b2/lec.txt','b2/lec2.txt')
// var data=fs.readFileSync("b2/lec2.txt",'utf-8')
// console.log(data)
// fs.unlinkSync('b2/lec2.txt')
// fs.rmdirSync('b2')